CREATE TABLE `crawler_ithome` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) DEFAULT '' COMMENT '标题',
  `url` VARCHAR(256) DEFAULT '' COMMENT 'url',
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '日期',
  `content` TEXT COMMENT '内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='IT之家新闻';
